# Generated by Django 5.2.17 on 2026-09-09 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Açıq'), ('reviewing', 'İncələnir'), ('resolved', 'Həll edildi'), ('dismissed', 'Rədd edildi')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_note', models.TextField(blank=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_complaints', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
