# Generated by Django 5.2.17 on 2026-09-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coinclaim_coinpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('spam', 'Spam və reklam'), ('harassment', 'Təhqir və narahat etmə'), ('fake', 'Saxta profil'), ('inappropriate', 'Uyğunsuz məzmun'), ('other', 'Digər')], default='other', max_length=30),
        ),
    ]
